virtualStoreType: global

minimumReleaseAgeExclude:
  - "@mr-hope/*"
  - "@oxfmt/*"
  - "@oxlint/*"
  - "oxc-config-hope"
  - "oxfmt"
  - "oxlint"
  - "tsdown"

trustPolicy: no-downgrade

trustPolicyExclude:
  # babel
  - semver@5.7.2
minimumReleaseAgeExcludePrune: true
trustPolicyExcludePrune: true
trustPolicyIgnoreAfter: 720
